# Generated by Django 5.1.7 on 2025-03-20 17:10

import core.utils.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=core.utils.models.hex_uuid, editable=False, unique=True, verbose_name='Public ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=250, verbose_name='Categories name')),
            ],
            options={
                'db_table': 'courses_categories',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=core.utils.models.hex_uuid, editable=False, unique=True, verbose_name='Public ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=200, verbose_name='Course name')),
                ('short_description', models.CharField(max_length=300, verbose_name='Course short description')),
                ('full_description', models.TextField(verbose_name='Course full description')),
                ('teaser', models.FileField(null=True, upload_to=None, verbose_name='Course teaser')),
                ('coast', models.PositiveSmallIntegerField(verbose_name='Course cost')),
                ('status', models.IntegerField(choices=[(-1, 'Cancelled'), (1, 'Requires attention'), (0, 'Work in progress'), (2, 'Complete')], default=0, verbose_name='Course status')),
                ('duration', models.TimeField(verbose_name='Course duration')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses_categories', verbose_name='Course category')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Courses_Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=core.utils.models.hex_uuid, editable=False, unique=True, verbose_name='Public ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=200, verbose_name='Sections name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.courses', verbose_name='Course')),
            ],
            options={
                'db_table': 'courses_sections',
            },
        ),
        migrations.CreateModel(
            name='Section_Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=core.utils.models.hex_uuid, editable=False, unique=True, verbose_name='Public ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(default='Test', max_length=200, verbose_name='Lesson name')),
                ('video', models.FileField(null=True, upload_to=None, verbose_name='Lesson section video')),
                ('description', models.TextField(verbose_name='Lesson section description')),
                ('duration', models.TimeField(verbose_name='Lesson section duration')),
                ('additional_materials', models.FileField(null=True, upload_to=None, verbose_name='Lesson section additional materials')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.courses_sections', verbose_name='Course section')),
            ],
            options={
                'db_table': 'section_lessons',
            },
        ),
        migrations.CreateModel(
            name='Lessons_Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=core.utils.models.hex_uuid, editable=False, unique=True, verbose_name='Public ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('content', models.FileField(null=True, upload_to=None, verbose_name='Lesson content')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section_lessons', verbose_name='Course section lesson')),
            ],
            options={
                'db_table': 'lessons_materials',
            },
        ),
    ]
