# Generated by Django 5.1.7 on 2025-04-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.CharField(choices=[('CL', 'Cancelled'), ('RA', 'Requires attention'), ('WIP', 'Work in progress'), ('CT', 'Complete')], default='RA', max_length=3, verbose_name='Course status'),
        ),
    ]
