# Generated by Django 5.1.7 on 2025-04-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.CharField(choices=[('CL', 'Cancelled'), ('WIP', 'Work in progress'), ('RA', 'Requires attention'), ('CT', 'Complete')], default='WIP', max_length=3, verbose_name='Course status'),
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['-created'], name='courses_created_829945_idx'),
        ),
    ]
