# Generated by Django 5.1.7 on 2025-04-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_options_alter_courses_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='courses',
            name='courses_created_829945_idx',
        ),
    ]
