# Generated by Django 5.1.7 on 2025-04-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['-created']},
        ),
    ]
