# Generated by Django 5.1.7 on 2025-04-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses_sections',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='lessons_materials',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='section_lessons',
            options={'ordering': ['-created']},
        ),
        migrations.AddIndex(
            model_name='courses',
            index=models.Index(fields=['-created'], name='courses_created_829945_idx'),
        ),
        migrations.AddIndex(
            model_name='courses_sections',
            index=models.Index(fields=['-created'], name='courses_sec_created_b354b4_idx'),
        ),
        migrations.AddIndex(
            model_name='lessons_materials',
            index=models.Index(fields=['-created'], name='lessons_mat_created_bb63b2_idx'),
        ),
        migrations.AddIndex(
            model_name='section_lessons',
            index=models.Index(fields=['-created'], name='section_les_created_4d19eb_idx'),
        ),
    ]
