# Generated by Django 5.1.7 on 2025-05-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_courses_sections_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="duration",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Course duration"
            ),
        ),
    ]
