# Generated by Django 5.1.7 on 2025-05-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_courses_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section_lessons",
            name="duration",
            field=models.TimeField(null=True, verbose_name="Lesson section duration"),
        ),
    ]
