# Generated by Django 5.1.7 on 2025-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_section_lessons_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section_lessons",
            name="additional_materials",
        ),
        migrations.RemoveField(
            model_name="section_lessons",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="section_lessons",
            name="video",
        ),
        migrations.AlterField(
            model_name="lessons_materials",
            name="content",
            field=models.CharField(
                default="https:localhost:5432/api/v1/test",
                max_length=250,
                verbose_name="Lesson content",
            ),
        ),
    ]
