# Generated by Django 5.1.7 on 2025-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_remove_section_lessons_additional_materials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons_materials",
            name="content",
            field=models.FileField(
                null=True, upload_to="uploads/", verbose_name="Lesson content"
            ),
        ),
    ]
