# Generated by Django 5.1.7 on 2025-06-06 07:08

import core.s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_lessons_materials_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons_materials",
            name="content",
            field=models.FileField(
                storage=core.s3_storage.ClientDocsStorage(), upload_to=""
            ),
        ),
    ]
