# Generated by Django 5.1.7 on 2025-06-11 05:43

import core.s3_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_lessons_materials_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessons_materials",
            name="content",
            field=models.FileField(
                max_length=400, storage=core.s3_storage.ClientDocsStorage, upload_to=""
            ),
        ),
    ]
