# Generated by Django 5.1.7 on 2025-06-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_alter_lessons_materials_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessons_materials",
            name="url",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
